export const employees = [
    {
      id: "1269",
      firstName: "Arun",
      lastName: "Gupta",
      company: "Amazon",
      bio: "Arun Gupta is a Principal Open Source Technologist at Amazon Web Services.",
      twitterHandle: "arungupta",
      favorite: true,
      leaveDays: 20, 
      startDate: "2020-05-15",
      leaveRequests: [
        {
          id: "1",
          startDate: "2023-01-10",
          endDate: "2023-01-15",
          type: "Vacation",
          status: "Approved",
        },
      ],
      tasks: [
        {
          id: "1",
          title: "Complete Project X",
          description: "Finish the project milestone by the end of the month.",
          status: "In Progress",
        },
      ],
      messages: [
        {
          id: "1",
          sender: "John Doe",
          content: "Meeting at 2 PM today.",
          timestamp: "2023-01-12T14:00:00Z",
        },
      ],
      position: "Software Engineer",
      role: "Full Stack Developer",
      department: "Engineering",
      salary: 90000,
      hourlyRate: 45,
      employeeImage: "/path/to/employee-picture.jpg",
    },
    {
      id: "1270",
      firstName: "Jane",
      lastName: "Smith",
      company: "Microsoft",
      bio: "Jane Smith is a Senior Software Engineer at Microsoft.",
      twitterHandle: "janesmith",
      favorite: false,
      leaveDays: 18,
      startDate: "2019-08-20",
      leaveRequests: [
        {
          id: "2",
          startDate: "2023-02-15",
          endDate: "2023-02-20",
          type: "Sick Leave",
          status: "Pending",
        },
      ],
      tasks: [
        {
          id: "2",
          title: "Bug Fixing",
          description: "Address critical bugs reported by the QA team.",
          status: "Completed",
        },
      ],
      messages: [
        {
          id: "2",
          sender: "John Doe",
          content: "Please review the latest code changes.",
          timestamp: "2023-02-25T10:15:00Z",
        },
      ],
      position: "Software Engineer",
      role: "Backend Developer",
      department: "Engineering",
      salary: 85000,
      hourlyRate: 40,
      employeeImage: "/path/to/jane-picture.jpg",
    },
    {
      id: "1271",
      firstName: "Mark",
      lastName: "Johnson",
      company: "Google",
      bio: "Mark Johnson is a Product Manager at Google.",
      twitterHandle: "markjohnson",
      favorite: true,
      leaveDays: 25,
      startDate: "2018-03-10",
      leaveRequests: [],
      tasks: [],
      messages: [],
      position: "Product Manager",
      role: "Product Strategy",
      department: "Product Management",
      salary: 110000,
      hourlyRate: null,
      employeeImage: "/path/to/mark-picture.jpg",
    },
    {
      id: "1272",
      firstName: "Emily",
      lastName: "Davis",
      company: "Apple",
      bio: "Emily Davis is a UI/UX Designer at Apple.",
      twitterHandle: "emilydavis",
      favorite: false,
      leaveDays: 22,
      startDate: "2021-06-05",
      leaveRequests: [
        {
          id: "3",
          startDate: "2023-03-01",
          endDate: "2023-03-05",
          type: "Vacation",
          status: "Pending",
        },
      ],
      tasks: [],
      messages: [],
      position: "UI/UX Designer",
      role: "Design",
      department: "Design",
      salary: 95000,
      hourlyRate: null,
      employeeImage: "/path/to/emily-picture.jpg",
    },
    {
      id: "1273",
      firstName: "David",
      lastName: "Brown",
      company: "Amazon",
      bio: "David Brown is a Senior Software Engineer at Amazon Web Services.",
      twitterHandle: "davidbrown",
      favorite: true,
      leaveDays: 18,
      startDate: "2017-12-15",
      leaveRequests: [
        {
          id: "4",
          startDate: "2023-04-15",
          endDate: "2023-04-20",
          type: "Sick Leave",
          status: "Pending",
        },
      ],
      tasks: [
        {
          id: "3",
          title: "New Feature Development",
          description: "Implement a new feature requested by the product team.",
          status: "Not Started",
        },
      ],
      messages: [],
      position: "Software Engineer",
      role: "Full Stack Developer",
      department: "Engineering",
      salary: 95000,
      hourlyRate: 45,
      employeeImage: "/path/to/david-picture.jpg",
    },
    {
      id: "1274",
      firstName: "Sarah",
      lastName: "Adams",
      company: "Amazon",
      bio: "Sarah Adams is a Product Manager at Amazon Web Services.",
      twitterHandle: "sarahadams",
      favorite: false,
      leaveDays: 25,
      startDate: "2016-05-20",
      leaveRequests: [
        {
          id: "5",
          startDate: "2023-05-10",
          endDate: "2023-05-20",
          type: "Vacation",
          status: "Approved",
        },
      ],
      tasks: [],
      messages: [],
      position: "Product Manager",
      role: "Product Strategy",
      department: "Product Management",
      salary: 115000,
      hourlyRate: null,
      employeeImage: "/path/to/sarah-picture.jpg",
    },
  ];
  
  